import sys
import os
from pathlib import Path
# Ensure project_paths.py is found at the root
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))


"""
Pipeline Phase 1: Feature Selection for Deep Features
-----------------------------------------------------
Input: deep_features.csv (Generated by extract_deep_features.py)
Logic:
1. Load Deep Features (2048 dims).
# CRITICAL: We need labels. This script assumes we can merge with a label file.
# Since this is an independent experiment, we will try to find labels in the source directory
# or expect a labels.csv.
# adaptation: I will try to load labels from the known 'isic_clean.csv' location if possible, 
# or raise error if 'labels.csv' is missing.
"""

import os
import json
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import mutual_info_classif
from project_paths import DEEP_FEATURES_FILE, FEATURE_SELECTION_METADATA_FILE, CUSTOM_LABELS_FILE

# Configuration
SCRIPT_DIR = Path(__file__).parent.resolve()
FEATURE_FILE = DEEP_FEATURES_FILE
METADATA_FILE = FEATURE_SELECTION_METADATA_FILE
RANDOM_SEED = 42

# Path to ground truth labels (Linking to known location)
# If this moves, we need a local labels.csv
LABEL_SOURCE_PATH = CUSTOM_LABELS_FILE

def run_selection_pipeline():
    if not FEATURE_FILE.exists():
        print(f"Error: {FEATURE_FILE} not found. Run extraction first!")
        return

    print("Step 1: Loading Deep Features...")
    df_feats = pd.read_csv(FEATURE_FILE)
    print(f"  Loaded {len(df_feats)} instances with {df_feats.shape[1]-1} features.")

    # Step 1.5: Merge with Labels
    # We need to map image_id to valid labels.
    # The 'image_id' in extraction was just the filename (e.g. ISIC_0000000)
    # The isic_clean.csv usually has 'image' column.
    
    if not LABEL_SOURCE_PATH.exists():
        print(f"Error: Label source not found at {LABEL_SOURCE_PATH}")
        print("Please provide a 'labels.csv' with 'image' and 'label' columns.")
        return
        
    print(f"  Loading Labels from {LABEL_SOURCE_PATH}...")
    df_labels = pd.read_csv(LABEL_SOURCE_PATH)
    
    # We assume df_labels has 'image' (ID) and 'label' (Binary target)
    if 'image' not in df_labels.columns or 'label' not in df_labels.columns:
        print("Error: Label file must contain 'image' and 'label' columns.")
        # Try to infer if column 0 implies image index... risky.
        return

    # Merge
    # Ensure ID formats match. Extraction uses filename stem.
    # Check one ID
    print("  Merging Features with Labels...")
    df_merged = pd.merge(df_feats, df_labels[['image', 'label']], left_on='image_id', right_on='image', how='inner')
    
    if len(df_merged) == 0:
        print("CRITICAL WARNING: Merge resulted in 0 records. Check ID formats!")
        print(f"  Feature IDs example: {df_feats['image_id'].iloc[0]}")
        print(f"  Label IDs example: {df_labels['image'].iloc[0]}")
        return
        
    print(f"  Merged Dataset Size: {len(df_merged)}")
    
    # Prepare X, y
    drop_cols = ['image_id', 'image', 'label']
    feature_cols = [c for c in df_merged.columns if c not in drop_cols]
    
    X = df_merged[feature_cols].values
    y = df_merged['label'].values
    
    # Split (Same seed as champion)
    X_train, _, y_train, _ = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=RANDOM_SEED
    )
    
    print(f"Step 2: Ranking {len(feature_cols)} Deep Features by Mutual Information...")
    
    mi_scores = mutual_info_classif(X_train, y_train, random_state=RANDOM_SEED)
    
    # --- SUPERVISOR UPDATE: Option A (Redundancy Removal) ---
    # 1. Select Top 300 by MI first
    initial_k = 300
    if len(feature_cols) < initial_k:
        initial_k = len(feature_cols)
        
    top_300_indices = np.argsort(mi_scores)[-initial_k:][::-1]
    
    print(f"Step 3: Removing Correlated Features (Pearson > 0.9) from Top {initial_k}...")
    X_top_300 = X_train[:, top_300_indices]
    df_top = pd.DataFrame(X_top_300, columns=[feature_cols[i] for i in top_300_indices])
    
    # Calculate Correlation Matrix
    corr_matrix = df_top.corr().abs()
    
    # Select upper triangle of correlation matrix
    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
    
    # Find features with correlation greater than 0.9
    to_drop = [column for column in upper.columns if any(upper[column] > 0.9)]
    
    print(f"  Dropped {len(to_drop)} redundant features.")
    
    # Filter
    final_features = df_top.drop(columns=to_drop)
    final_feature_names = final_features.columns.tolist()
    
    # Map back to original indices
    # We need indices relative to the ORIGINAL X_train for the training script
    final_indices = [feature_cols.index(name) for name in final_feature_names]
    
    # Start Step 4 (limit to 200 if we still have too many?)
    # Supervisor said "Top 200" originally, but "300 -> Remove" might leave ~150-250.
    # Let's keep what remains to be safe, up to a reasonable max.
    
    print(f"  Final Selection Count: {len(final_indices)}")
    
    # Save Metadata
    metadata = {
        "source": "ResNet50_AvgPool_RedundancyAware",
        "base_features": feature_cols, # All valid cols
        "top_indices": final_indices,
        "top_feature_names": final_feature_names,
        "seed": RANDOM_SEED,
        "note": "MI Top 300 filtered by Pearson > 0.9"
    }
    
    # Log top 3
    print(f"Top 3 Deep Features: {final_feature_names[:3]}")
    
    with open(METADATA_FILE, 'w') as f:
        json.dump(metadata, f, indent=4)
        
    print(f"SUCCESS! Metadata saved to {METADATA_FILE}")

if __name__ == "__main__":
    run_selection_pipeline()
